// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import ScrollToBottomOfMessagesController from "./scroll_to_bottom_of_messages_controller";
application.register(
  "scroll-to-bottom-of-messages",
  ScrollToBottomOfMessagesController
);
